cnmv_nifs: "A-28294726"
# üóùÔ∏è Palabras clave para buscar en las noticias.
# Puedes poner una o varias entre comillas. 
# Si no quieres filtro, deja las comillas vac√≠as: ""
keywords:
  - "code"
  - "rule"
  - "regulation"
  - "low carbon"
  - "industry"
  - "industrial"
  - "methodology"
  - "sandbox"
  - "regulates"
  - "regulatory"
  - "ley"
  - "decreto"
  - "aprueba"
  - "reglas"
  - "regulaci√≥n"
  - "ley"
  - "aprueba" 
  - "reglas"
  - "regulaci√≥n"
  - "energ√≠a"
  - "energ√©tico"
  - "electricidad"
  - "gas"
  - "renovable"
  - "bater√≠as"
  - "solar"
  - "e√≥lica"


# üåç Zona horaria (normalmente no se toca).
# Si est√°s en Espa√±a, deja "Europe/Madrid".
tzname: "Europe/Madrid"

# ‚è±Ô∏è Cu√°ntas horas hacia atr√°s se buscan noticias recientes.
# 24 significa "√∫ltimas 24 horas".
hours_recent: 24

# üìß A qu√© correos se enviar√° el resumen.
# Puedes a√±adir m√°s poniendo cada uno en una l√≠nea nueva con "-".
email:
  user: "ggarcia@eve.eus"   # remitente
  to_emails:
    - "ggarcia@eve.eus"     # destinatarios

# üåê Medios o p√°ginas de donde se sacan las noticias.
# Puedes a√±adir o quitar medios f√°cilmente copiando un bloque.
# Cada bloque necesita un nombre, una URL y el n√∫mero m√°ximo de art√≠culos.
sources:
  - name: "UK"
    url: "https://www.ofgem.gov.uk/news-and-insight/press-releases"
    max_to_fetch: 400
  - name: "UK2"
    url: "https://www.ofgem.gov.uk/consultations/consultations-and-calls-input"
    max_to_fetch: 400
  - name: "UK3"
    url: "https://www.gov.uk/government/organisations/department-for-energy-security-and-net-zero"
    max_to_fetch: 400
  - name: "Italia"
    url: " https://www.mase.gov.it/portale/web/guest/comunicati-stampa"
    max_to_fetch: 400
  - name: "CRE"
    url: "https://www.cre.fr/actualites/toute-lactualite.html"
    max_to_fetch: 400
  - name: "BMWE"
    url: "https://www.recht.bund.de/SiteGlobals/Forms/Suche/Expertensuche_Formular.html?resourceId=196172&input_=196116&pageLocale=de&templateQueryString=Elektrizit%C3%A4t%20und%20Gas&submit=Suchen&lastChangeVdAfter=&lastChangeVdBefore=&lastChangeAdAfter=&lastChangeAdBefore=&bgblnr=&fnanr=&gestanr=&federfuehrung=&federfuehrung.GROUP=1&cl2Categories_year=2025&cl2Taxonomies_Sachgebiete_fq=%22Wirtschaftsrecht/Bergbau,%20Kernenergie,%20Elektrizit%C3%A4t,%20Gas,%20Wasserwirtschaft,%20Energieversorgung%22#search-extended"
    max_to_fetch: 400
  - name: "ERSE"
    url: "https://www.erse.pt/biblioteca/legislacao/"
    max_to_fetch: 400
  - name: "Noticias juridicas"
    url: "https://noticias.juridicas.com/base_datos/"
    max_to_fetch: 400
  
 
